INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (1, 'Finalizou a trilha introdutória de Python', 'Python Iniciante', 'TRILHA', 300);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (2, 'Domine a base da linguagem', 'Conquista: Sintaxe', 'MODULO', 100);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (3, 'Controle o fluxo de execução', 'Conquista: Condicionais', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (4, 'Repita tarefas com eficiência', 'Conquista: Laços', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (5, 'Você sabe criar uma página simples do zero!', 'Web Básico', 'TRILHA', 250);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (6, 'Domine o HTML semântico', 'Conquista: HTML', 'MODULO', 100);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (7, 'Dê estilo às páginas com eficiência', 'Conquista: CSS', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (8, 'Você conhece o JavaScript moderno!', 'JS Essentials', 'TRILHA', 400);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (9, 'Entenda os tipos e escopos', 'Conquista: Variáveis JS', 'MODULO', 90);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (10, 'Domine o uso de funções', 'Conquista: Funções', 'MODULO', 100);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (11, 'Interaja com o HTML dinamicamente', 'Conquista: DOM', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (12, 'Controle interações do usuário', 'Conquista: Eventos', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (13, 'Você está pronto para React!', 'React Developer', 'TRILHA', 350);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (14, 'Utilize JSX corretamente', 'Conquista: JSX', 'MODULO', 100);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (15, 'Entenda o fluxo de dados', 'Conquista: Props & State', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (16, 'Use os principais hooks', 'Conquista: Hooks', 'MODULO', 140);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (17, 'Você entende a base dos algoritmos!', 'Lógica Básica', 'TRILHA', 220);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (18, 'Domine os fundamentos do pseudocódigo', 'Conquista: Variáveis', 'MODULO', 90);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (19, 'Controle decisões no algoritmo', 'Conquista: Condicional', 'MODULO', 110);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (20, 'Você domina as principais estruturas de dados!', 'Data Structures', 'TRILHA', 500);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (21, 'Aprenda a armazenar dados eficientemente', 'Conquista: Coleções', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (22, 'Gerencie dados com LIFO', 'Conquista: Pilha', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (23, 'Organize elementos de forma sequencial', 'Conquista: Fila', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (24, 'Conecte dados de forma flexível', 'Conquista: Lista Ligada', 'MODULO', 140);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (25, 'Associe dados eficientemente', 'Conquista: Mapas', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (26, 'Você criou seu primeiro app Android com Kotlin!', 'Kotlin Mobile', 'TRILHA', 450);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (27, 'Entenda a sintaxe da linguagem Kotlin', 'Conquista: Kotlin', 'MODULO', 110);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (28, 'Construa a interface do app', 'Conquista: Layouts', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (29, 'Gerencie a lógica das telas', 'Conquista: Activity', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (30, 'Implemente transições entre telas', 'Conquista: Navegação', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (31, 'Você criou sua primeira aplicação Flutter!', 'Flutter Iniciante', 'TRILHA', 300);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (32, 'Preparou o ambiente para desenvolvimento', 'Conquista: Setup', 'MODULO', 90);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (33, 'Construa interfaces com Flutter', 'Conquista: Widgets', 'MODULO', 120);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (34, 'Navegue entre páginas no app', 'Conquista: Navegação Flutter', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (35, 'Você domina a criação e publicação de containers!', 'Container Expert', 'TRILHA', 350);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (36, 'Entenda a diferença entre containers e VMs', 'Conquista: Containers', 'MODULO', 110);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (37, 'Monte imagens funcionais', 'Conquista: Dockerfile', 'MODULO', 130);
INSERT INTO public.conquistas (id, descricao, nome, tipo, xp_ganho) VALUES (38, 'Compartilhe seus containers', 'Conquista: Docker Hub', 'MODULO', 120);
