INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (1, 17798, 1, 'Sintaxe Básica', 2, 1);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (2, 17799, 2, 'Estruturas Condicionais', 3, 1);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (3, 17800, 3, 'Laços de Repetição', 4, 1);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (4, 17801, 1, 'Estrutura HTML', 6, 2);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (5, 17802, 2, 'Estilização com CSS', 7, 2);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (6, 17803, 1, 'Declaração de Variáveis', 9, 3);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (7, 17804, 2, 'Funções em JS', 10, 3);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (8, 17805, 3, 'Manipulação do DOM', 11, 3);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (9, 17806, 4, 'Eventos e Formulários', 12, 3);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (10, 17807, 1, 'Componentes e JSX', 14, 4);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (11, 17808, 2, 'Props e Estado', 15, 4);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (12, 17809, 3, 'Hooks Essenciais', 16, 4);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (13, 17810, 1, 'Variáveis e Operadores', 18, 5);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (14, 17811, 2, 'Algoritmos Condicionais', 19, 5);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (15, 17812, 1, 'Arrays e Coleções', 21, 6);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (16, 17813, 2, 'Pilhas (Stacks)', 22, 6);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (17, 17814, 3, 'Filas (Queues)', 23, 6);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (18, 17815, 4, 'Listas Ligadas', 24, 6);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (19, 17816, 5, 'Mapas e Dicionários', 25, 6);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (20, 17817, 1, 'Kotlin Básico', 27, 7);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (21, 17818, 2, 'Layouts com XML', 28, 7);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (22, 17819, 3, 'Activity e Ciclo de Vida', 29, 7);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (23, 17820, 4, 'Intents e Navegação', 30, 7);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (24, 17821, 1, 'Configuração do Ambiente', 32, 8);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (25, 17822, 2, 'Widgets Básicos', 33, 8);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (26, 17823, 3, 'Navegação com Routes', 34, 8);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (27, 17824, 1, 'Conceitos de Containers', 36, 9);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (28, 17825, 2, 'Dockerfile na Prática', 37, 9);
INSERT INTO public.modulos (id, conteudo, ordem, titulo, conquista_id, trilha_id) VALUES (29, 17826, 3, 'Publicação com Docker Hub', 38, 9);
